/*
Documentation of AI usage for "debouncing"

I will paste all prompts here, but not all outputs (since it's alot)

I will paste the outputs that are enough to understand what's going on

Note: Initially I thought that "sleeping" would be the best method, but
as I've been shown, debouncing is a better option

Model: ChatGPT (April 2026)
Prompts used:

First attempt at trying to sleep
1) thread sleep for 0.5 seconds javascripy

Realising that the thread outputted wasn't working correctly. Note this was ChatGPT's solution from the first prompt
It was here that it suggested debouncing as well
2) const performSearchFilter = async (value) => { // Await for 0.1 seconds as "minimum" for filtering // This is to avoid flickering of the loading spinner await new Promise(resolve => setTimeout(resolve, 1000)); not awaiting

Asking how to implement debounce
3) debounce, but for react bootstrap

Making it specific for this use case
4) [Pasted in specific code in our code base] how to implement debounce for this function

Trying to understand how debounce works
5) please explain what's happening in debounce here: [pasted in code that was generated by GPT]

Asked to make it re-usable
6) "If you want, I can help you turn this into a reusable hook (useDebounce)—that’s the kind of thing reviewers actually like seeing." do this

Then GPT made this file
*/
import { useRef } from 'react';

export function useDebouncedCallback(callback, delay = 200) {
  const timeoutRef = useRef(null);

  return (...args) => {
    clearTimeout(timeoutRef.current);

    timeoutRef.current = setTimeout(() => {
      callback(...args);
    }, delay);
  };
}
